Homework3
made-ml-in-prod-2021/garistvlad pull request #4
Opened 2021-06-04 21:15 UTC by garistvlad

0. Поднимите airflow локально, используя docker compose
`Done.`

1. (5 баллов) Реализуйте dag, который генерирует данные для обучения модели
`Done.`
За это отвечает dag `load_dataset`, беря данные из `sklearn.datasets.load_diabetes` и добавляя шум во время каждого запуска.

2. (10 баллов) Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. В вашем пайплайне должно быть как минимум 4 стадии.
`Done.`
В dag-е `train_model` 5 стадий (не считая DummyOperator и FileSensors): split -> fit_transformer -> transform -> fit_model -> validate

3. (5 баллов) Реализуйте dag, который использует модель ежедневно
`Done.`
Реализовано в dag-е `predict`

3.1. (3 доп балла) Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения
`Done.`
Сенсоры использую как в `train_model`, так и в `predict`

4. вы можете выбрать 2 пути для выполнения ДЗ. 
- поставить все необходимые пакеты в образ с airflow и использовать bash operator, python operator (0 баллов)
- использовать DockerOperator, тогда выполнение каждой из тасок должно запускаться в собственном контейнере
-- 1 из дагов реализован с помощью DockerOperator (5 баллов)
-- все даги реализованы только с помощью DockerOperator (10 баллов)
`Done.`
Все dag-и реализованы с помощью DockerOperator. Образы собираются исходя из Dockerfile-ов в категории `images`, как в примере у Михаила.

5. Протестируйте ваши даги (5 баллов) https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html 
`Done.`
Протестировал именно dag-и, тесты сложил в директорию `/tests`. Тестирование обучения модели, валидации и инференса не делал, поскольку это было в предыдущих ДЗ + не требовалось в задании.

6. В docker compose так же настройте поднятие mlflow и запишите туда параметры обучения, метрики и артефакт(модель) (5 доп баллов)
`Skipped`

7. вместо пути в airflow variables  используйте апи Mlflow Model Registry (5 доп баллов)
`Skipped`

8. Настройте alert в случае падения дага (3 доп. балла)
`Done`
Настроил уведомления на свою Yandex почту, прописав параметры SMTP.

9. традиционно, самооценка (1 балл)
`Done`

**Total: 42 балла**

2021-06-13 15:00 UTC, Mikhail-M commented
Вы считаете нормальным, не добавлять преподавателей в ревью?)

2021-06-16 13:42 UTC, Mikhail-M requested changes
ДАвайте, чтобы был код только третьей дз, а то меня это уже начинает раздражать(дело не в вас, просто часто такое вижу)

Как исправите -- верните в работу

2021-06-16 22:07 UTC, garistvlad commented
> ДАвайте, чтобы был код только третьей дз, а то меня это уже начинает раздражать(дело не в вас, просто часто такое вижу)
> 
> Как исправите -- верните в работу

Да, пропустил это. Сейчас исправлено, в ветке только файлы для hw3.

2021-06-17 07:41 UTC, Mikhail-M commented on airflow-dags/dags/dag_predict.py
> +from airflow.utils.dates import days_ago
За этот даг 2 балла, так как не используется Variables, модель находится по захардкоженному пути

2021-06-17 07:42 UTC, Mikhail-M reviewed
тесты -- 2.5 балла
кажется , что тут было бы уместнее написать побольше маленьких и проверить какие-то частные свойства, чем делать такую параметризацию, в общем случае, под все даги такое не напишешь

2021-06-17 07:44 UTC, Mikhail-M approved these changes
Баллы: 36.5

2021-06-19 19:59 UTC, merged